export const capsuleConstants = {
  ALL_CAPSULES_REQUEST: "ALL_CAPSULES_REQUEST",
  ALL_CAPSULES_SUCCESS: "ALL_CAPSULES_SUCCESS",
  ALL_CAPSULES_FAIL: "ALL_CAPSULES_FAIL",

  CAPSULE_DETAILS_REQUEST: "CAPSULE_DETAILS_REQUEST",
  CAPSULE_DETAILS_SUCCESS: "CAPSULE_DETAILS_SUCCESS",
  CAPSULE_DETAILS_FAIL: "CAPSULE_DETAILS_FAIL",

  CLEAR_ERRORS: "CLEAR_ERRORS",
};
