export const capsuleConstants = {
  ALL_CAPSULES_REQUEST: "ALL_CAPSULES_REQUEST",
  ALL_CAPSULES_SUCCESS: "ALL_CAPSULES_SUCCESS",
  ALL_CAPSULES_FAIL: "ALL_CAPSULES_FAIL",

  CLEAR_ERRORS: "CLEAR_ERRORS",
};
